# --------------------------------------------------------------------------
# Set all defaults
set_defaults: &parent_defaults
  backdate_days_start: 90
  backdate_days_end: 1
  target_run_date: ~
  target_run_end_date: ~
  date_format: '%Y-%m-%d'
  storage_account: jonoaoedlext 
  container: landing
  base_url: https://aoestats.io
  dir_url: '/media/db_dumps/date_range%3D'
  params: ~

# Each datasource is given its own key and values, inherited from defaults
datasource:
  metadata:
    <<: *parent_defaults
    endpoint: '/api/db_dumps.json'
    suffix: metadata

  relic:
    <<: *parent_defaults
    base_url: https://aoe-api.worldsedgelink.com
    endpoint: '/community/leaderboard/getLeaderBoard2?'
    suffix: relic
    params: 
      leaderboard_id: 3
      title: age2
      sort_by: 0
      chunk_size: 100 

  matches:
    <<: *parent_defaults
    suffix: 'matches'
    prefix: 'matches'

  players:
    <<: *parent_defaults
    suffix: 'players'
    prefix: 'players'
