# --------------------------------------------------------------------------
# Set all defaults
set_defaults: &parent_defaults
  backdate_days_start: 20
  backdate_days_end: 5
  target_run_date: ~
  target_run_end_date: ~
  date_format: '%Y-%m-%d'
  storage_account: jonoaoedlext 
  base_url: https://aoestats.io
  dir_url: '/media/db_dumps/date_range%3D'
  params: ~

# Each datasource is given its own key and values, inherited from defaults
datasource:
  metadata:
    <<: *parent_defaults
    container_suffix: meta
    endpoint: '/api/db_dumps.json'
    suffix: metadata

  relic:
    <<: *parent_defaults
    container_suffix: rl_api
    base_url: https://aoe-api.worldsedgelink.com
    endpoint: '/community/leaderboard/getLeaderBoard2?'
    suffix: relic
    params: 
      leaderboard_id: 3
      title: age2
      sort_by: 0
      chunk_size: 100 

  matches:
    <<: *parent_defaults
    container_suffix: 'matches'
    suffix: 'matches'
    prefix: 'matches'
    cast_mapping:
      raw_match_type: float64


  players:
    <<: *parent_defaults
    container_suffix: players
    suffix: 'players'
    prefix: 'players'
    cast_mapping:
      profile_id: Int64
      replay_summary_raw: object

  country_list:
    <<: *parent_defaults
    container_suffix: country_list
    file_name: 'country_list.csv' 
