name: CD Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_and_run_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Install project
      #   run: |
      #     pip install -e .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt 

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=${GITHUB_WORKSPACE}/src" >> $GITHUB_ENV

      - name: Run Databricks Job for Prod
        env:
          CATALOG_ENV: PROD
        run: |
          python src/orchestration/run_all.py