name: CI Workflow

on: 
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    name: Lint & Format Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt 
      
      - name: Run_linting_with_Ruff
        run: ruff check .
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Check for linting errors
        if: steps.Run_linting_with_Ruff.outcome == 'failure'
        run: echo "Linting errors found. Please fix and re-commit."
        continue-on-error: true 

      - name: Run tests with pytest
        run: |
          pytest src/ingestion/zzz_ingestion_tests.py